### ISSUE TITLE
Please add support for Eigen

### ISSUE THREAD

**Issue by ongbe** [CoolmanCZ/upp_cmake#2]
。/uppsrc/plugin/Eigen/unsupported/Eigen/NonLinearOptimization:15: error: Eigen/Core: No such file or directory
 #include <Eigen/Core>
          ^~~~~~~~~~~~

**Comment by CoolmanCZ** [comment]
Hi,

Try latest commit 7746fff14dbe179e352a49412876077f95c5fa31.

BR, Radek

**Comment by CoolmanCZ** [comment]
Hi, please try latest version.
